server:
  port: 8888
  contextPath: /

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: mail.bookstorage.kr
    port: 587
    username: ksb@bookstorage.kr
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email-upload-path: /home/whilemouse/email